# Generated by Django 3.2.15 on 2022-09-21 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(verbose_name='Уникальное название урока')),
                ('title', models.CharField(max_length=120, verbose_name='Название урока')),
                ('desc', models.TextField(verbose_name='Описание урока')),
                ('number', models.IntegerField(verbose_name='Номер урока')),
                ('video', models.CharField(max_length=100, verbose_name='Ссылка на видео урок')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.courses', verbose_name='Какой курс?')),
            ],
        ),
    ]
