# Generated by Django 3.2.15 on 2022-09-22 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_lesson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Уникальное название курса'),
        ),
    ]
