# Generated by Django 3.2.15 on 2022-09-19 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220919_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='sender',
            field=models.IntegerField(default=11, verbose_name='подписка на рассылку'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('male', 'мужской пол'), ('female', 'женский пол')], max_length=10, verbose_name='пол'),
        ),
    ]
