# Generated by Django 3.2.15 on 2022-09-19 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20220919_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('male', 'мужской пол'), ('female', 'женский пол')], default='male', max_length=10, verbose_name='пол'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sender',
            field=models.BooleanField(default=1, verbose_name='подписка на рассылку'),
        ),
    ]
